spring:
  application:
    name: api-gateway
  security:
    oauth2:
      client:
        registration:
          gateway-client:
            provider: auth-server
            client-id: gateway-client
            client-secret: gateway-secret
            authorization-grant-type: authorization_code
            scope: openid,profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          auth-server:
            issuer-uri: http://localhost:9000

      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000

server:
  port: 8080

eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

# OpenAPI configuration
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: User Service
        url: /v3/api-docs/users

      - name: Product Service
        url: /v3/api-docs/products

      - name: Inventory Service
        url: /v3/api-docs/inventories

      - name: Order Service
        url: /v3/api-docs/orders

      - name: Auth Server
        url: /v3/api-docs/auth
  disable-swagger-default-url: true
  operations-sorter: alpha
  tags-sorter: alpha
  display-request-duration: true
