spring:
  application:
    name: payment-service

  kafka:
    bootstrap-servers: localhost:9092

  # Database configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/paymentdb
    username: ${PAYMENT_DB_USER}
    password: ${PAYMENT_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  database-platform: org.hibernate.dialect.PostgreSQLDialect

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8005
