spring:
  application:
    name: payment-service

  kafka:
    bootstrap-servers: localhost:9092

  # Database configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/paymentdb
    username: ${PAYMENT_DB_USER}
    password: ${PAYMENT_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format-sql: true

server:
  port: ${SERVER_PORT:0}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
